load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "localtime",
    srcs = ["localtime.cpp"],
    hdrs = ["localtime.hpp"]
)

cc_library(
    name = "greet",
    srcs = ["greet.cpp"],
    hdrs = ["greet.hpp"]
)
